In [1]:
from packaging import version

import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from scipy import stats
import tensorboard as tb

In [4]:
major_ver, minor_ver, _ = version.parse(tb.__version__).release
assert major_ver >= 2 and minor_ver >= 3, \
    "This notebook requires TensorBoard 2.3 or later."
print("TensorBoard version", tb.__version__, "works for experimental purposes!")

TensorBoard version 2.8.0 works for experimental purposes!

In [9]:
experiment_id = "F2K2zZnlQzinJHv7To50fA"
experiment = tb.data.experimental.ExperimentFromDev(experiment_id)
df = experiment.get_scalars()
df

,run,tag,step,value
0,"MonetDense__[128, 128]__[0]__0__synthetic2",epoch,9,0.000000
1,"MonetDense__[128, 128]__[0]__0__synthetic2",epoch,19,0.000000
2,"MonetDense__[128, 128]__[0]__0__synthetic2",epoch,29,0.000000
3,"MonetDense__[128, 128]__[0]__0__synthetic2",epoch,39,0.000000
4,"MonetDense__[128, 128]__[0]__0__synthetic2",epoch,49,0.000000
...,...,...,...,...
1105675,"MonetDense__[128, 128]__[0]__60__synthetic2",val_loss: mse,1289679,0.168415
1105676,"MonetDense__[128, 128]__[0]__60__synthetic2",val_loss: mse,1312709,0.163510
1105677,"MonetDense__[128, 128]__[0]__60__synthetic2",val_loss: mse,1335739,0.161328
1105678,"MonetDense__[128, 128]__[0]__60__synthetic2",val_loss: mse,1358769,0.167273
1105679,"MonetDense__[128, 128]__[0]__60__synthetic2",val_loss: mse,1381799,0.167568